[dependencies]
base = "0.9.0"
btree = "https://github.com/canscale/StableHeapBTreeMap#v0.3.2"
stable-hash-map = "https://github.com/canscale/StableHashMap#v0.2.1"
stable-rbtree = "https://github.com/canscale/StableRBTree#v0.6.1"
candy = "https://github.com/icdevs/candy_library#0.3.0"
stablebuffer = "https://github.com/skilesare/StableBuffer#v0.2.0"
map = "https://github.com/ZhenyaUsenko/motoko-hash-map#v7.0.0"
array = "https://github.com/aviate-labs/array.mo#v0.2.0"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.3.2"