[dependencies]
base = "0.9.0"
stable-hash-map = "https://github.com/canscale/StableHashMap#v0.2.1"
stable-rbtree = "https://github.com/canscale/StableRBTree#v0.3.0"
array = "https://github.com/aviate-labs/array.mo#v0.2.0"
io = "https://github.com/aviate-labs/io.mo#v0.3.1"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.3.2"
rand = "https://github.com/aviate-labs/rand.mo#v0.2.2"
ulid = "https://github.com/ByronBecker/ulid.mo#v0.1.2"
stablebuffer = "https://github.com/skilesare/StableBuffer#v0.2.0"
map = "https://github.com/ZhenyaUsenko/motoko-hash-map#v7.0.0"
candy = "https://github.com/icdevs/candy_library#0.3.0"